title: Fillbert
tagline: "The Empty Space Cat"
description: "A vector-based webcomic starring the empty space cat"
baseurl: "/fillbert"
url: "https://mincerafter42.github.io"
timezone: Etc/GMT

exclude: [README.md]
future: true
kramdown:
 smart_quotes: "39,39,34,34"

date_format: "%G-W%V"

defaults:
 - 
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 - 
  scope:
   path: ""
   type: "posts"
  values:
   layout: "comic"
 -
  scope:
   path: "img/*.svg"
  values:
   layout: "compressxml"
