title: Fillbert
description: "The Empty Space Cat"
baseurl: "/fillbert"
url: "https://mincerafter42.github.io"
timezone: America/Vancouver

future: true
kramdown:
 smart_quotes: "39,39,34,34"

date_format: "%G-W%V"

defaults:
 - 
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 - 
  scope:
   path: ""
   type: "posts"
  values:
   layout: "comic"
 -
  scope:
   path: "img/*.svg"
  values:
   layout: "compressxml"
